### ISSUE TITLE
Missing 'cypress' from copy path in split.yml merge-reports job?

### ISSUE THREAD

**Issue by nerrante** [bahmutov/cypress-workflows#19]
Hi Gleb,
Was playing around with your split workflow and I ran into a problem.  I set up everything as you show in your examples and in your [blogpost](https://glebbahmutov.com/blog/the-awesome-battle/), but when it gets to the merge step, it can't find the files because they don't get copied down. I think it is because it is missing "cypress" as part of the directory path.  Let me know what you think.

From the split.yml, under the merge-reports job:
```- name: Copy all assets and JSON reports
        run: |
          cp -r split-results/cypress-split-results-*/screenshots/* mochawesome/screenshots || true
          cp -r split-results/cypress-split-results-*/videos/* mochawesome/videos || true
          cp -r split-results/cypress-split-results-*/results/* mochawesome/results || true
```

I believe it just needs to be changed to:
```- name: Copy all assets and JSON reports
        run: |
          cp -r split-results/cypress-split-results-*/cypress/screenshots/* mochawesome/screenshots || true
          cp -r split-results/cypress-split-results-*/cypress/videos/* mochawesome/videos || true
          cp -r split-results/cypress-split-results-*/cypress/results/* mochawesome/results || true
```

**Comment by FluffyBubu** [comment]
@nerrante I was having the same problem. I built the file again manually from Gleb's [code](https://github.com/bahmutov/cypress-workflows/blob/main/.github/workflows/split.yml) and can confirm that that fixed it on my side 👍

**Comment by dusty-phillips** [comment]
@bahmutov any advice here? I tried removing `reportDir` from the recommended reporterOptions but it still fails to find them. Looks like a new release is in order?

**Comment by bahmutov** [comment]
@nerrante or @dusty-phillips can you open a PR with the fix, please?

**Comment by dusty-phillips** [comment]
@bahmutov PR here: https://github.com/bahmutov/cypress-workflows/pull/23 and I confirmed it is now working for my local setup. 

One note: I'm not sure caching is working correctly because the test/merge-results task seems to be installing dependencies from scratch again. The total runtime of my job is actually longer than if I run it in non-parallel mode on the default cypress action (which may just be a sign that I need to run more tests), and the billable minutes consumed is about 2x.
